#sdk: "C:/RhoMobileSuite5.2.2/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.2.2"
sdkversion: "5.2.0"
name: "RhoPerfaler"
version: 1.0
vendor: "rhomobile"
build: "debug"
app_type: "rhoelements"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator8.2"
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.rhoperfaler"
  BundleURLScheme: "rhoperfaler"
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
wp8:
  productid: "fea92ee0-0281-0133-ef33-00155d000300"
android:
#manifest_template: 'AndroidManifest.erb'
  version: "2.3.3"
  logcatFilter: "APP:I StrictMode:I DEBUG:I *:E"
  capabilities:
    - hardware_acceleration
wm: 
win32:
  deployqt: 1
  deploymsvc: 1
extensions:
  - rhodes_translator
  - rhoconnect-client
  - printing
  - printing_zebra
rhobundle:
  exclude_items:
    - thumb.db
capabilities:
  - non_motorola_device
  - gps
  - vibrate
  - bluetooth
  - network_state
